/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caseStudy;

import javax.swing.JOptionPane;

/**
 *
 * @author User01
 */
public class creditCardPaymentFrame extends javax.swing.JFrame {
    Variables v = new Variables();

    /**
     * Creates new form creditCardPaymentFrame
     */
    public creditCardPaymentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        paymentButton = new javax.swing.JButton();
        back = new javax.swing.JButton();
        tf3 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        total3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Credit Card Payment");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Card Holder Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 81, -1, -1));

        tf1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 81, 355, 47));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setText("Card Number:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 143, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setText("Pin Code:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 212, -1, -1));

        tf2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 143, 434, 47));

        paymentButton.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        paymentButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                paymentButtonStateChanged(evt);
            }
        });
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(paymentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 440, 57));

        back.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 24, -1, -1));
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 211, 509, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseStudy/parlorBackground5.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        total3.setText("jLabel5");
        getContentPane().add(total3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        String input1 = tf1.getText(), input2 = tf2.getText(), input3 = tf3.getText();
        
        if((input1.isEmpty() || input2.isEmpty() || input3.isEmpty())){
            JOptionPane.showMessageDialog(null, "Please Enter All Of Your Information", "Information Error", JOptionPane.ERROR_MESSAGE);
        }else{
            thankYouFrame fm4 = new thankYouFrame();
            fm4.setVisible(true);
            receipt fm6 = new receipt();
            
            paymentMethodFrame fm3 = new paymentMethodFrame();
            String totalString = total3.getText();
            
            if (totalString.equalsIgnoreCase("250.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("999.0")){
                fm6.serviceLabel1.setText("Hair Color                                 ₱999");
                fm6.serviceLabel2.setText("");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("1999.0")){
                fm6.serviceLabel1.setText("Hair Rebond                              ₱1999");
                fm6.serviceLabel2.setText("");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("2499.0")){
                fm6.serviceLabel1.setText("Hair Perm                                ₱2499");
                fm6.serviceLabel2.setText("");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("1249.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Color                                 ₱999");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("2249.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Rebond                             ₱1999");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("2749.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Perm                               ₱2499");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("2998.0")){
                fm6.serviceLabel1.setText("Hair Color                                 ₱999");
                fm6.serviceLabel2.setText("Hair Rebond                             ₱1999");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("3498.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Perm                               ₱2499");
                fm6.serviceLabel3.setText("");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("3248.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Color                                 ₱999");
                fm6.serviceLabel3.setText("Hair Rebond                              ₱1999");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            if (totalString.equalsIgnoreCase("3748.0")){
                fm6.serviceLabel1.setText("Haircut                                     ₱250");
                fm6.serviceLabel2.setText("Hair Color                                 ₱999");
                fm6.serviceLabel3.setText("Hair Perm                                ₱2499");
                fm6.serviceTotal.setText("₱" + totalString);
            }
            fm6.setVisible(true);
            dispose();
            
        }
        
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void paymentButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_paymentButtonStateChanged
        
    }//GEN-LAST:event_paymentButtonStateChanged

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        menuFrame fm2 = new menuFrame();
        fm2.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creditCardPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creditCardPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creditCardPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creditCardPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creditCardPaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JButton paymentButton;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JPasswordField tf3;
    public javax.swing.JLabel total3;
    // End of variables declaration//GEN-END:variables
}
