/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caseStudy;

import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 *
 * @author User01
 */
public class menuFrame extends javax.swing.JFrame {
    Variables v = new Variables();

    String servicePick2;
    int total;

    /**
     * Creates new form menuFrame
     */
    public menuFrame() {
       
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        choice1 = new java.awt.Choice();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jProgressBar1 = new javax.swing.JProgressBar();
        jToggleButton4 = new javax.swing.JToggleButton();
        label1 = new java.awt.Label();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        servicesPicked = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hairService1 = new javax.swing.JToggleButton();
        hairService2 = new javax.swing.JToggleButton();
        hairService3 = new javax.swing.JToggleButton();
        hairService4 = new javax.swing.JToggleButton();
        done = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jToggleButton4.setText("Haircut                                                               ₱ 250");
        jToggleButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        label1.setText("label1");

        jCheckBox1.setText("jCheckBox1");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseStudy/parlorBackground5.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseStudy/parlorBackground3.jpg"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 350));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 173, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 35, -1, -1));

        total1.setText("       ");
        getContentPane().add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 27, 63, -1));

        servicesPicked.setText("                  ");
        getContentPane().add(servicesPicked, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 59, -1, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setText("Price");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setText("Hair Services");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        hairService1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hairService1.setText("Haircut                                                               ₱ 250");
        hairService1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hairService1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairService1ActionPerformed(evt);
            }
        });
        getContentPane().add(hairService1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 616, -1));

        hairService2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hairService2.setText("Hair Color                                                           ₱ 999");
        hairService2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hairService2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hairService2MouseClicked(evt);
            }
        });
        hairService2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairService2ActionPerformed(evt);
            }
        });
        getContentPane().add(hairService2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 616, -1));

        hairService3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hairService3.setText("Hair Rebond                                                      ₱ 1999");
        hairService3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hairService3.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        hairService3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hairService3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hairService3StateChanged(evt);
            }
        });
        hairService3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairService3ActionPerformed(evt);
            }
        });
        getContentPane().add(hairService3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 616, -1));

        hairService4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        hairService4.setText("Hair Perm                                                          ₱ 2499");
        hairService4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hairService4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hairService4ActionPerformed(evt);
            }
        });
        getContentPane().add(hairService4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 616, -1));

        done.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        done.setText("Done");
        done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneActionPerformed(evt);
            }
        });
        getContentPane().add(done, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        back.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseStudy/parlorBackground5.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hairService2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairService2ActionPerformed
        boolean serviceStatus = true;
    }//GEN-LAST:event_hairService2ActionPerformed

    private void hairService1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairService1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hairService1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void hairService3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairService3ActionPerformed

        if (hairService3.isSelected()) {
        hairService4.setSelected(false); // Unselect hairService4
    }
        
    }//GEN-LAST:event_hairService3ActionPerformed

    private void hairService3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hairService3StateChanged
        
    }//GEN-LAST:event_hairService3StateChanged

    private void hairService2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hairService2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hairService2MouseClicked

    private void hairService4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hairService4ActionPerformed
        if (hairService4.isSelected()) {
            hairService3.setSelected(false); // Unselect hairService3
        }
    }//GEN-LAST:event_hairService4ActionPerformed

    private void doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneActionPerformed
        if (!(hairService1.isSelected() || hairService2.isSelected() || hairService3.isSelected() || hairService4.isSelected())){
            JOptionPane.showMessageDialog(null, "Please Pick A Service", "Service Error", JOptionPane.ERROR_MESSAGE);
        }else {
            double total = 0;
            String a = System.lineSeparator();
            String servicePick1 = "", servicePick2 = "",servicePick4 = "";
            int servicePrice = 0;
            if (hairService1.isSelected()){
                total += 250;
                servicePick1 += (String) hairService1.getText() + a;
                servicePick2 += "Haircut " + a;
                servicePrice += 250;
            }
            if (hairService2.isSelected()){
                total += 999;
                servicePick1 += (String) hairService2.getText() + a;
                servicePick2 += "Hair Color " + a;
                servicePrice += 999;
            }
            if (hairService3.isSelected()){
                total += 1999;
                servicePick1 += (String) hairService3.getText() + a;
                servicePick2 += "Hair Rebond" + a;
                servicePrice += 1999;
            }
            if (hairService4.isSelected()){
                total += 2499;
                servicePick1 += (String) hairService4.getText();
                servicePick2 += "Hair Perm";
                servicePrice += 2499;
            }
            
            int confirm = JOptionPane.showConfirmDialog(null,
                            "Are you sure you want to place this order?\n"
                                    + servicePick1 + "\n"
                                            
                                    + "Total Bill: ₱" + String.format("%.2f", total) + "\n"
                    , "Confirm Order", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION){
                menuFrame fm2 = new menuFrame();
                String totalString = String.valueOf(total);
                
                total1.setText(totalString);
                servicesPicked.setText(servicePick2);
                paymentMethodFrame fm3 = new paymentMethodFrame();
                fm3.setVisible(true);
                fm3.total2.setText(totalString);
                setVisible(false);
                System.out.println(v.getusername());
            }
        }
    }//GEN-LAST:event_doneActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        welcomeFrame fm1 = new welcomeFrame();
        fm1.setVisible(true);
        menuFrame fm2 = new menuFrame();
        dispose();
        
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private java.awt.Choice choice1;
    public javax.swing.JButton done;
    private javax.swing.Box.Filler filler1;
    public javax.swing.JToggleButton hairService1;
    public javax.swing.JToggleButton hairService2;
    public javax.swing.JToggleButton hairService3;
    public javax.swing.JToggleButton hairService4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JToggleButton jToggleButton4;
    private java.awt.Label label1;
    private javax.swing.JLabel servicesPicked;
    public javax.swing.JLabel total1;
    // End of variables declaration//GEN-END:variables
}
