/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package caseStudy;
import java.sql.*;
import java.time.LocalDate;
/**
 *
 * @author User01
 */
public class paymentMethodFrame extends javax.swing.JFrame {
    Variables v = new Variables();

    private Date date;
        
    /**
     * Creates new form paymentMethodFrame
     */
    public paymentMethodFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        total2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        ServicePicked2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment Method");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setText("Payment Method");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 47, -1, -1));

        jButton1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jButton1.setText("Over The Counter");
        jButton1.setMaximumSize(new java.awt.Dimension(361, 54));
        jButton1.setMinimumSize(new java.awt.Dimension(361, 54));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 217, 361, 155));

        jButton2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jButton2.setText("Credit Card Payment");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 217, -1, 155));

        total2.setForeground(new java.awt.Color(255, 255, 255));
        total2.setText("          ");
        total2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                total2MouseClicked(evt);
            }
        });
        total2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                total2PropertyChange(evt);
            }
        });
        getContentPane().add(total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 66, -1, -1));

        back.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 24, -1, -1));

        ServicePicked2.setText("              ");
        getContentPane().add(ServicePicked2, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 83, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caseStudy/parlorBackground5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addToDatabase();   
        welcomeFrame fm1 = new welcomeFrame();
        thankYouFrame fm4 = new thankYouFrame();
        menuFrame fm2 = new menuFrame();
        receipt fm6 = new receipt();
        
        String totalString = total2.getText();
        
        if (totalString.equalsIgnoreCase("250.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
            
            
            
        }
        if (totalString.equalsIgnoreCase("999.0")){
            fm6.serviceLabel1.setText("Hair Color                                 ₱999");
            fm6.serviceLabel2.setText("");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("1999.0")){
            fm6.serviceLabel1.setText("Hair Rebond                              ₱1999");
            fm6.serviceLabel2.setText("");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("2499.0")){
            fm6.serviceLabel1.setText("Hair Perm                                ₱2499");
            fm6.serviceLabel2.setText("");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("1249.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Color                                 ₱999");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("2249.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Rebond                             ₱1999");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("2749.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Perm                               ₱2499");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("2998.0")){
            fm6.serviceLabel1.setText("Hair Color                                 ₱999");
            fm6.serviceLabel2.setText("Hair Rebond                             ₱1999");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("3498.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Perm                               ₱2499");
            fm6.serviceLabel3.setText("");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("3248.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Color                                 ₱999");
            fm6.serviceLabel3.setText("Hair Rebond                              ₱1999");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        if (totalString.equalsIgnoreCase("3748.0")){
            fm6.serviceLabel1.setText("Haircut                                     ₱250");
            fm6.serviceLabel2.setText("Hair Color                                 ₱999");
            fm6.serviceLabel3.setText("Hair Perm                                ₱2499");
            fm6.serviceTotal.setText("₱" + totalString);
        }
        
        fm4.setVisible(true);
        fm6.setVisible(true);
        
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void addToDatabase() {
        
        
        String url = "jdbc:mysql://localhost:3306/parlorearnings";
        String username = "root";
        String password = "leoneiljaime25";
        String query = "INSERT INTO productspurchased(service_name, service_date, price)VALUES(?,?,?)";
        
        try ( Connection conn = DriverManager.getConnection(url, username, password);) {
            
            PreparedStatement stmt = conn.prepareStatement(query);
            paymentMethodFrame fm3 = new paymentMethodFrame();
            menuFrame fm2 = new menuFrame();
            LocalDate date = LocalDate.now();
            
            stmt.setString(1, fm2.servicePick2);
            
            stmt.setDate(2, fm3.date);
            stmt.setInt(3, (int) Double.parseDouble(total2.getText()));
            stmt.executeQuery();
            System.out.println("Ordered!");
            
        } catch (SQLException e) {
            
        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        menuFrame fm2 = new menuFrame();
        paymentMethodFrame fm3 = new paymentMethodFrame();
        creditCardPaymentFrame fm5 = new creditCardPaymentFrame();
        fm5.setVisible(true);
        String totalString = total2.getText();
        
        fm5.paymentButton.setText("Pay ₱" + totalString);
        fm5.total3.setText(totalString);
        setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        menuFrame fm2 = new menuFrame();
        fm2.setVisible(true);
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void total2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_total2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_total2MouseClicked

    private void total2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_total2PropertyChange
        total2.setForeground(new java.awt.Color(0, 0, 0, 0));
    }//GEN-LAST:event_total2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(paymentMethodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(paymentMethodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(paymentMethodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(paymentMethodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new paymentMethodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ServicePicked2;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
