/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package caseStudy;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author User01
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
        
        Icon i = receiptImage.getIcon();
        ImageIcon icon = (ImageIcon)i;
        Image image = icon.getImage().getScaledInstance(receiptImage.getWidth(),receiptImage.getHeight(), Image.SCALE_SMOOTH);
        receiptImage.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        service1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serviceLabel1 = new javax.swing.JLabel();
        serviceTotal = new javax.swing.JLabel();
        serviceLabel2 = new javax.swing.JLabel();
        serviceLabel3 = new javax.swing.JLabel();
        receiptImage = new javax.swing.JLabel();

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParlorImage/parlorReceipt.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        service1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(service1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 105, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 157, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 227, -1, -1));

        serviceLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        serviceLabel1.setText("Service1");
        serviceLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                serviceLabel1PropertyChange(evt);
            }
        });
        getContentPane().add(serviceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 440, -1));

        serviceTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        serviceTotal.setText("total");
        getContentPane().add(serviceTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 130, 30));

        serviceLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        serviceLabel2.setText("Service2");
        getContentPane().add(serviceLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 440, -1));

        serviceLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        serviceLabel3.setText("Service3");
        getContentPane().add(serviceLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 450, -1));

        receiptImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParlorImage/parlorReceipt.png"))); // NOI18N
        getContentPane().add(receiptImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void serviceLabel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_serviceLabel1PropertyChange
        
    }//GEN-LAST:event_serviceLabel1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel receiptImage;
    public javax.swing.JLabel service1;
    public javax.swing.JLabel serviceLabel1;
    public javax.swing.JLabel serviceLabel2;
    public javax.swing.JLabel serviceLabel3;
    public javax.swing.JLabel serviceTotal;
    // End of variables declaration//GEN-END:variables
}
